update dumps to follow python 3.6 types (required for cloudpickle v1.3) to fix - AttributeError: module 'types' has no attribute 'ClassType'
- this is due to drop of pyhton2 support in cloudpickle v1.3
  (e.g. the following conversion has been removed  `types.ClassType = type`)